// AUTO-GENERATED by scripts/generate-palettes.mjs - do not edit directly.
// Rerun `nx run tokens:build` after changing that script's BRANDS map.

/**
 * Business-unit brand names, mirroring Angular Material's own prebuilt-theme
 * naming (azure-blue.css, rose-red.css, ...). Unlike light/dark/high-contrast
 * mode, brand is chosen once at install time, not switched at runtime - each
 * brand is a separate CSS/SCSS bundle under `dist/{css,scss,json}/brands/
 * <brand>/`, and a team picks the one for their business unit.
 */
export const BRAND_NAMES = [
  'azure-blue',
  'rose-red',
  'cyan-orange',
] as const;

export type BrandName = (typeof BRAND_NAMES)[number];
