// Generates one entry file per business-unit brand and compiles each to
// dist/<brand>.css - Bootstrap compiled with that brand's token values baked
// in, mirroring Angular Material's own azure-blue.css/rose-red.css/...
// convention. The entry files are generated rather than hand-written so that
// adding a brand is a single edit to packages/tokens' BRANDS map.
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generateBrandEntries,
  compileBrandThemes,
} from '../../tools/scripts/brand-theme-build.mjs';

const packageDir = dirname(fileURLToPath(import.meta.url));

generateBrandEntries(
  packageDir,
  (brand) => `// AUTO-GENERATED by compile-themes.mjs - do not edit directly.
// Bootstrap 5 compiled with the "${brand}" business-unit brand's tokens.
// Pick the entry matching your business unit - mirroring Angular Material's
// own ${brand}.css convention.
@import '@app-design-system/tokens/dist/scss/_core.scss';
@import '@app-design-system/tokens/dist/scss/brands/${brand}/_theme-light.scss';
@import '../scss/bootstrap-variable-mapping';
@import 'bootstrap/scss/bootstrap';
`,
);

compileBrandThemes(packageDir);
