// Generates a Sass palette map from the tokens package's tonal palette JSON,
// shaped exactly as Angular Material's `mat.define-theme()` expects for its
// `color.primary` config: tone keys (0-100) at the map's root, plus nested
// `secondary` / `neutral` / `neutral-variant` / `error` sub-maps. Angular
// Material's own M3 theme generator builds this same shape from a seed
// color using the same HCT/tonal-palette algorithm
// (@material/material-color-utilities) - this script just points that
// algorithm's *output* (already computed once in packages/tokens) at
// Material's Sass input format, so the org's brand colors - not Material's
// bundled placeholder palettes - drive every themed component.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const palette = JSON.parse(
  readFileSync(resolve(__dirname, '../tokens/dist/json/palette.json'), 'utf-8'),
).palette;

const toneMap = (scale) =>
  `(\n${Object.entries(scale)
    .map(([tone, hex]) => `    ${tone}: ${hex},`)
    .join('\n')}\n  )`;

const primaryMap = `(\n${Object.entries(palette.primary)
  .map(([tone, hex]) => `  ${tone}: ${hex},`)
  .join('\n')}\n  secondary: ${toneMap(palette.secondary)},\n  neutral: ${toneMap(palette.neutral)},\n  neutral-variant: ${toneMap(palette['neutral-variant'])},\n  error: ${toneMap(palette.error)},\n)`;

const tertiaryMap = `(\n${Object.entries(palette.tertiary)
  .map(([tone, hex]) => `  ${tone}: ${hex},`)
  .join('\n')}\n)`;

const scss = `// AUTO-GENERATED by build.mjs from packages/tokens - do not edit directly.
$app-primary-palette: ${primaryMap};

$app-tertiary-palette: ${tertiaryMap};
`;

mkdirSync(resolve(__dirname, 'generated'), { recursive: true });
writeFileSync(resolve(__dirname, 'generated/_app-palettes.scss'), scss);
console.log('Wrote generated/_app-palettes.scss');
