// Generates one entry file per business-unit brand and compiles each to
// dist/<brand>.css - one compiled Material theme per business unit, mirroring
// Angular Material's own separate azure-blue.css/rose-red.css/... files.
// The entry files are generated rather than hand-written so that adding a
// brand is a single edit to packages/tokens' BRANDS map.
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generateBrandEntries,
  compileBrandThemes,
} from '../../tools/scripts/brand-theme-build.mjs';

const packageDir = dirname(fileURLToPath(import.meta.url));

generateBrandEntries(
  packageDir,
  (brand) => `// AUTO-GENERATED by compile-themes.mjs - do not edit directly.
// Angular Material theme for the "${brand}" business-unit brand. Import this
// instead of a bare "theme" - pick the entry matching your business unit,
// mirroring Angular Material's own ${brand}.css convention.
@use '../theme-mixin' as theme;
@use '../../generated/${brand}/app-palettes' as palettes;

@include theme.app-theme(
  palettes.$app-primary-palette,
  palettes.$app-tertiary-palette
);
`,
);

compileBrandThemes(packageDir);
